CREATE TABLE INVOICES(
	id SERIAL PRIMARY KEY,
	rowId INT,
	data DATE,
	lungime REAL, 
	latime REAL, 
	profilareL1 REAL, 
	profilareL2 REAL, 
	profilareLstg REAL, 
	profilareLdr REAL, 
	picuratorL1 REAL, 
	picuratorL2 REAL, 
	picuratorLstg REAL, 
	picuratorLdr REAL, 
	nrBuc REAL, 
	taiereML REAL,
	profilare REAL,
	picurator REAL,
	suprafata REAL,
	decupajeLavoare REAL,
	decupajePeCurb REAL,
	gauriCarota REAL,
	lipireAdaos REAL,
	canalAntiderapant REAL
);
