INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ALLURE ROYALE', 2, 'LUSTRUIT', 'LASTRE', 838.13, 997.37);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ALMOND MAUVE ', 2, 'LUSTRUIT', 'SEMILASTRE', 416.25, 495.34);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AMARELLO ROSA', 2, 'LUSTRUIT', 'LASTRE', 416.25, 495.34);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AMARELLO ROSA', 3, 'LUSTRUIT', 'LASTRE', 556.88, 662.68);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AMARELLO ROSA', 2, 'LUSTRUIT', 'SEMILASTRE', 309.38, 368.16);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AMARELLO ROSA', 2, 'FIAMAT', 'SEMILASTRE', 292.5, 348.08);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AMARELLO ROSA', 3, 'LUSTRUIT', 'SEMILASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AMARELLO ROSA', 3, 'FIAMAT', 'SEMILASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AMARULA', 2, 'LUSTRUIT', 'LASTRE', 708.75, 843.41);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AMAZONIA V/C', 2, 'LUSTRUIT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ANTICO BORDEAUX', 2, 'LUSTRUIT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ANTICO BORDEAUX', 1.8, 'LUSTRUIT', 'SEMILASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ARACRUZ BLACK', 2, 'LUSTRUIT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ARUBA GOLD ', 2, 'LUSTRUIT', 'LASTRE', 978.75, 1164.71);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ARUBA GOLD ', 3, 'LUSTRUIT', 'LASTRE', 1395, 1660.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ASCON WHITE', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ASH BLUE', 2, 'LUSTRUIT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ASHEN WHITE', 3, 'LUSTRUIT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ASPEN WHITE', 2, 'LUSTRUIT', 'LASTRE', 382.5, 455.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ASTORIA', 2, 'LUSTRUIT', 'LASTRE', 506.25, 602.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AUDAX LIGHT', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AVALANCHE', 2, 'LUSTRUIT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AVORIO', 2, 'LUSTRUIT', 'LASTRE', 1125, 1338.75);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AVORIO', 3, 'LUSTRUIT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AZUL NOCHE ', 2, 'LUSTRUIT', 'LASTRE', 787.5, 937.13);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AZUL PLATINO ', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AZUL PLATINO ', 2, 'FIAMAT', 'LASTRE', 613.13, 729.62);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AZUL PLATINO ', 3, 'LUSTRUIT', 'LASTRE', 888.75, 1057.61);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AZUL WHITE', 2, 'LUSTRUIT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AZUL WHITE', 1.8, 'LUSTRUIT', 'SEMILASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'AZURITE', 2, 'LUSTRUIT', 'LASTRE', 2221.88, 2644.03);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BAHAMA GOLD', 2, 'LUSTRUIT', 'LASTRE', 697.5, 830.03);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BALTIC BROWN ', 2, 'LUSTRUIT', 'LASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BALTIC BROWN ', 3, 'LUSTRUIT', 'LASTRE', 1068.75, 1271.81);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO ANTICO', 2, 'LUSTRUIT', 'LASTRE', 838.13, 997.37);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO ANTICO', 3, 'LUSTRUIT', 'LASTRE', 1743.75, 2075.06);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO CRYSTAL', 2, 'LUSTRUIT', 'LASTRE', 360, 428.4);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO CRYSTAL', 3, 'LUSTRUIT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO CRYSTAL', 2, 'FIAMAT', 'SEMILASTRE', 264.38, 314.61);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO CRYSTAL', 2, 'LUSTRUIT', 'SEMILASTRE', 247.5, 294.53);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO CRYSTAL', 3, 'FIAMAT', 'SEMILASTRE', 360, 428.4);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO CRYSTAL', 3, 'LUSTRUIT', 'SEMILASTRE', 348.75, 415.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO PRIMATA', 2, 'LUSTRUIT', 'LASTRE', 388.13, 461.87);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO PRIMATA', 3, 'LUSTRUIT', 'LASTRE', 405, 481.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO ROMANO', 2, 'LUSTRUIT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO ROMANO', 3, 'LUSTRUIT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO TAUPE', 2, 'LUSTRUIT', 'LASTRE', 798.75, 950.51);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO TROPICAL', 2, 'LUSTRUIT', 'LASTRE', 388.13, 461.87);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BIANCO TROPICAL', 3, 'LUSTRUIT', 'LASTRE', 405, 481.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLACK GALAXY', 2, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLACK GALAXY', 3, 'LUSTRUIT', 'LASTRE', 767.5, 913.33);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLACK GALAXY', 2, 'LUSTRUIT', 'SEMILASTRE', 432.5, 514.68);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLACK GALAXY', 3, 'LUSTRUIT', 'SEMILASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLACK MIST', 2, 'PERIAT', 'LASTRE', 821.25, 977.29);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLANC DU BLANC', 2, 'LUSTRUIT', 'LASTRE', 405, 481.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLANC DU BLANC', 3, 'LUSTRUIT', 'LASTRE', 489.38, 582.36);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLUE BAHIA ', 2, 'LUSTRUIT', 'LASTRE', 4106.25, 4886.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLUE PEARL', 2, 'LUSTRUIT', 'LASTRE', 1006.88, 1198.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BLUE PEARL', 3, 'LUSTRUIT', 'LASTRE', 1501.88, 1787.23);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BORDEAUX DREAM', 3, 'LUSTRUIT', 'LASTRE', 1743.75, 2075.06);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BRANCO CEARA ', 2, 'LUSTRUIT', 'LASTRE', 382.5, 455.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BRAZILIAN ARABESCATO', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BRAZILIAN BLACK', 2, 'LUSTRUIT', 'LASTRE', 596.25, 709.54);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BRAZILIAN BLACK', 2, 'PERIAT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BROWN ITABIRA', 3, 'LUSTRUIT', 'LASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BROWN PEARL', 2, 'LUSTRUIT', 'LASTRE', 405, 481.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BROWN PEARL', 3, 'LUSTRUIT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BUTTERFLY GREEN ', 2, 'LUSTRUIT', 'LASTRE', 607.5, 722.93);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'BUTTERFLY GREEN ', 3, 'LUSTRUIT', 'LASTRE', 877.5, 1044.23);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CALEDONIA', 3, 'LUSTRUIT', 'LASTRE', 405, 481.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CALIFORNIA DREAM', 2, 'LUSTRUIT', 'LASTRE', 1080, 1285.2);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CARAVELAS ', 2, 'LUSTRUIT', 'LASTRE', 573.75, 682.76);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CAT S EYE', 2, 'LUSTRUIT', 'LASTRE', 765, 910.35);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CAT S EYE', 3, 'LUSTRUIT', 'LASTRE', 1057.5, 1258.43);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CIANITUS', 2, 'LUSTRUIT', 'LASTRE', 1237.5, 1472.63);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CIELO', 2, 'LUSTRUIT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'COFEE BROWN', 2, 'LUSTRUIT', 'LASTRE', 392.5, 467.08);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'COFEE BROWN', 3, 'LUSTRUIT', 'LASTRE', 455, 541.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'COLONIAL CREAM', 3, 'LUSTRUIT', 'LASTRE', 455, 541.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'COLONIAL GOLD', 3, 'LUSTRUIT', 'LASTRE', 455, 541.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'COLONIAL WHITE', 3, 'LUSTRUIT', 'LASTRE', 455, 541.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CREMA GOLD', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CREMA GOLD', 3, 'LUSTRUIT', 'LASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CRISTALLO', 2, 'LUSTRUIT', 'LASTRE', 1113.75, 1325.36);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CRYSTAL YELLOW', 1.8, 'FIAMAT', 'SEMILASTRE', 331.88, 394.93);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'CRYSTAL YELLOW', 1.8, 'LUSTRUIT', 'SEMILASTRE', 315, 374.85);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'DALLAS WHITE', 2, 'LUSTRUIT', 'LASTRE', 405, 481.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'DALLAS WHITE', 3, 'LUSTRUIT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'DELIRIUM', 2, 'LUSTRUIT', 'LASTRE', 928.13, 1104.47);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'DIAMOND GALAXY', 2, 'LUSTRUIT', 'LASTRE', 596.25, 709.54);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'DIAMOND GALAXY', 2, 'PERIAT', 'LASTRE', 630, 749.7);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'DIAMOND GREEN', 2, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'DIAMOND GREEN', 3, 'LUSTRUIT', 'LASTRE', 765, 910.35);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'DUETTO', 2, 'LUSTRUIT', 'LASTRE', 1721.25, 2048.29);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ELEGANT BROWN', 2, 'LUSTRUIT', 'LASTRE', 838.13, 997.37);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EMERALD PEARL', 2, 'LUSTRUIT', 'LASTRE', 1147.5, 1365.53);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EMERALD PEARL', 3, 'LUSTRUIT', 'LASTRE', 1665, 1981.35);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EXODUS BLUE', 2, 'LUSTRUIT', 'LASTRE', 815.63, 970.59);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EXOTIC GOLD', 2, 'LUSTRUIT', 'LASTRE', 613.13, 729.62);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EXOTIC GOLD', 1.8, 'LUSTRUIT', 'SEMILASTRE', 522.5, 621.78);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EXOTIC JUPARANA', 2, 'LUSTRUIT', 'LASTRE', 706.88, 841.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EXOTIC JUPARANA', 1.8, 'LUSTRUIT', 'SEMILASTRE', 337.5, 401.63);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EXOTIC WHITE', 2, 'LUSTRUIT', 'LASTRE', 749.38, 891.76);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'EXOTIC WHITE', 1.8, 'LUSTRUIT', 'SEMILASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'FLASH GREEN', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'FLASH GREEN', 3, 'LUSTRUIT', 'LASTRE', 888.75, 1057.61);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'FOUR SEASONS', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'FROZEN PREMIUM', 3, 'PERIAT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'FUSION', 2, 'LUSTRUIT', 'LASTRE', 3307.5, 3935.93);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GAYA', 2, 'LUSTRUIT', 'LASTRE', 1715.63, 2041.59);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GERIBA', 3, 'LUSTRUIT', 'LASTRE', 562.5, 669.38);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO ANTICO 2.5 CM', 2.5, 'LUSTRUIT', 'LASTRE', 551.25, 655.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO CALIFORNIA', 2, 'LUSTRUIT', 'LASTRE', 810, 963.9);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO CALIFORNIA', 3, 'LUSTRUIT', 'LASTRE', 1248.75, 1486.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO CECILIA LIGHT S', 2, 'LUSTRUIT', 'LASTRE', 371.25, 441.79);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO CECILIA LIGHT S', 3, 'LUSTRUIT', 'LASTRE', 551.25, 655.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO FIORITO S', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO FIORITO S', 3, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO FIORITO', 2, 'LUSTRUIT', 'LASTRE', 432.5, 514.68);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO FIORITO', 3, 'LUSTRUIT', 'LASTRE', 1164.38, 1385.61);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLI NAPOLI', 2, 'LUSTRUIT', 'LASTRE', 412.5, 490.88);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO ORNAMENTAL S', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO ORNAMENTAL S', 3, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO ORNAMENTAL ', 2, 'LUSTRUIT', 'LASTRE', 810, 963.9);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO VICENZA', 2, 'LUSTRUIT', 'LASTRE', 412.5, 490.88);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO VENEZIANO', 2, 'LUSTRUIT', 'LASTRE', 551.25, 655.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIALLO YASMINE', 3, 'LUSTRUIT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GIBLEE GOLD', 2, 'LUSTRUIT', 'LASTRE', 506.25, 602.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GOLDEN BEACH', 3, 'LUSTRUIT', 'LASTRE', 455, 541.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GOLDEN CRYSTAL', 2, 'LUSTRUIT', 'LASTRE', 708.75, 843.41);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GOLDEN CRYSTAL', 2, 'PERIAT', 'LASTRE', 708.75, 843.41);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GOLDEN CRYSTAL', 3, 'LUSTRUIT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GOLDEN TYPHOON', 2, 'LUSTRUIT', 'LASTRE', 900, 1071);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GOLDEN TYPHOON', 3, 'LUSTRUIT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GREY GOOSE', 2, 'LUSTRUIT', 'LASTRE', 948.75, 1129.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS CADALSO', 2, 'LUSTRUIT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS MONDARIZ', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS MONDARIZ', 3, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS MONDARIZ', 2, 'FIAMAT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS MONDARIZ', 3, 'FIAMAT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS PERLA', 2, 'LUSTRUIT', 'LASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS PERLA', 3, 'LUSTRUIT', 'LASTRE', 607.5, 722.93);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS PERLA', 2, 'FIAMAT', 'LASTRE', 450, 535.5);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'GRIS PERLA', 3, 'FIAMAT', 'LASTRE', 607.5, 722.93);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ICARAI', 3, 'LUSTRUIT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IMPERIAL RED ', 2, 'LUSTRUIT', 'LASTRE', 652.5, 776.48);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IMPERIAL RED ', 3, 'FIAMAT', 'LASTRE', 911.25, 1084.39);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IMPERIAL RED ', 2, 'LUSTRUIT', 'SEMILASTRE', 506.25, 602.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IMPERIAL RED ', 2, 'FIAMAT', 'SEMILASTRE', 540, 642.6);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IMPERIAL RED ', 3, 'FIAMAT', 'SEMILASTRE', 787.5, 937.13);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IMPERIAL RED ', 3, 'LUSTRUIT', 'SEMILASTRE', 720, 856.8);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IMPERIAL GOLD', 3, 'LUSTRUIT', 'LASTRE', 455, 541.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'INDIANA GOLD', 2, 'LUSTRUIT', 'LASTRE', 596.25, 709.54);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IVORY BROWN', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IVORY BROWN', 2, 'LUSTRUIT', 'SEMILASTRE', 367.5, 437.33);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IVORY BROWN', 3, 'LUSTRUIT', 'SEMILASTRE', 607.5, 722.93);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IVORY FANTASY', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IVORY GOLD', 2, 'LUSTRUIT', 'LASTRE', 540, 642.6);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IVORY WAVES', 2, 'LUSTRUIT', 'LASTRE', 540, 642.6);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JACARANDA', 2, 'LUSTRUIT', 'LASTRE', 2486.25, 2958.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JAGUAR', 2, 'LUSTRUIT', 'LASTRE', 798.75, 950.51);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JAGUAR', 3, 'LUSTRUIT', 'LASTRE', 1051.88, 1251.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA COLOMBO', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA COLOMBO', 3, 'LUSTRUIT', 'LASTRE', 832.5, 990.68);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA COLOMBO', 2, 'LUSTRUIT', 'SEMILASTRE', 382.5, 455.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA COLOMBO', 2, 'FIAMAT', 'SEMILASTRE', 382.5, 455.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA GREY', 2, 'LUSTRUIT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA GREY', 3, 'LUSTRUIT', 'LASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA VENEZIANO', 3, 'LUSTRUIT', 'LASTRE', 438.75, 522.11);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA VENEZIANO', 3, 'MAT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'JUPARANA VENEZIANO', 3, 'PERIAT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'KASHMIR WHITE', 2, 'LUSTRUIT', 'SEMILASTRE', 438.75, 522.11);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'KASHMIR WHITE', 3, 'LUSTRUIT', 'SEMILASTRE', 641.25, 763.09);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'LEOPARD WHITE  g603', 2, 'LUSTRUIT', 'LASTRE', 450, 535.5);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'LEOPARD WHITE  g603', 3, 'LUSTRUIT', 'LASTRE', 551.25, 655.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'LEOPARD WHITE  g603', 2, 'LUSTRUIT', 'SEMILASTRE', 168.75, 200.81);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'LEOPARD WHITE  g603', 3, 'LUSTRUIT', 'SEMILASTRE', 365.63, 435.09);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'LEOPARD WHITE  g603', 2, 'FIAMAT', 'SEMILASTRE', 253.13, 301.22);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'LEOPARD WHITE  g603', 3, 'FIAMAT', 'SEMILASTRE', 348.75, 415.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MACAUBAS FANTASY', 2, 'LUSTRUIT', 'LASTRE', 1080, 1285.2);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MAGMA GOLD', 3, 'LUSTRUIT', 'LASTRE', 1136.25, 1352.14);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MAGMA', 2, 'LUSTRUIT', 'LASTRE', 1130.63, 1345.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MAGMA', 2, 'PERIAT', 'LASTRE', 933.75, 1111.16);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MAPLE RED ', 2, 'LUSTRUIT', 'LASTRE', 528.75, 629.21);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MAPLE RED ', 2, 'FIAMAT', 'SEMILASTRE', 348.75, 415.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MAPLE RED ', 2, 'LUSTRUIT', 'SEMILASTRE', 360, 428.4);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MAPLE RED ', 3, 'FIAMAT', 'SEMILASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MAPLE RED ', 3, 'LUSTRUIT', 'SEMILASTRE', 461.25, 548.89);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MARON COHIBA', 2, 'LUSTRUIT', 'LASTRE', 1383.75, 1646.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MARON COHIBA', 3, 'LUSTRUIT', 'LASTRE', 1968.75, 2342.81);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MASCALZONE', 2, 'LUSTRUIT', 'LASTRE', 1530, 1820.7);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MASCALZONE', 3, 'LUSTRUIT', 'LASTRE', 1293.75, 1539.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'METEORUS', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MIRACLE WHITE', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MIRACLE WHITE', 3, 'LUSTRUIT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MIRACLE WHITE', 2, 'LUSTRUIT', 'SEMILASTRE', 382.5, 455.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MONT BLANC', 2, 'LUSTRUIT', 'LASTRE', 708.75, 843.41);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MONT BLANC', 1.8, 'LUSTRUIT', 'SEMILASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MONTEROSA', 2, 'FIAMAT', 'SEMILASTRE', 315, 374.85);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MONTEROSA', 2, 'LUSTRUIT', 'SEMILASTRE', 303.75, 361.46);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MONTEROSA', 3, 'FIAMAT', 'SEMILASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MONTEROSA', 3, 'LUSTRUIT', 'SEMILASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MOON WHITE', 2, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MOON WHITE', 3, 'LUSTRUIT', 'LASTRE', 753.75, 896.96);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MULTICOLOR ', 2, 'LUSTRUIT', 'LASTRE', 392.5, 467.08);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MULTICOLOR ', 3, 'LUSTRUIT', 'LASTRE', 455, 541.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MULTICOLOR ', 2, 'FIAMAT', 'SEMILASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MULTICOLOR ', 2, 'LUSTRUIT', 'SEMILASTRE', 326.25, 388.24);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'MULTICOLOR ', 3, 'FIAMAT', 'SEMILASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NAPOLI CREAM', 2, 'LUSTRUIT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NAPOLI', 3, 'LUSTRUIT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NAPOLITTO', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NAPOLITTO', 3, 'LUSTRUIT', 'LASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NEGRO SAN RAFAEL', 3, 'PERIAT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NERO ZAMBIA', 2, 'LUSTRUIT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NERO ZAMBIA', 3, 'LUSTRUIT', 'LASTRE', 642.5, 764.58);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NERO ZAMBIA', 2, 'LUSTRUIT', 'SEMILASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NERO ZAMBIA', 3, 'LUSTRUIT', 'SEMILASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NETUNO BORDEAUX', 2, 'LUSTRUIT', 'LASTRE', 1080, 1285.2);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NETUNO BORDEAUX', 3, 'LUSTRUIT', 'LASTRE', 1552.5, 1847.48);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NEW CALEDONIA', 2, 'LUSTRUIT', 'LASTRE', 382.5, 455.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NEW MADURA GOLD', 2, 'LUSTRUIT', 'LASTRE', 641.25, 763.09);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NEW SOLARIUS', 2, 'LUSTRUIT', 'LASTRE', 528.75, 629.21);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NEW VENETIAN GOLD', 2, 'LUSTRUIT', 'LASTRE', 412.5, 490.88);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NEW WHITE TUULLUM', 2, 'LUSTRUIT', 'LASTRE', 405, 481.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'NORMANDY', 3, 'LUSTRUIT', 'LASTRE', 1743.75, 2075.06);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'OPERETA CREAM', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'OPERETA CREAM', 3, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'OPUS PEARL', 3, 'LUSTRUIT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ORNAMENTAL LIGHT S', 2, 'PERIAT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ORO BRASIL S', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ORO BRASIL S', 3, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ORO BRASIL', 2, 'LUSTRUIT', 'LASTRE', 412.5, 490.88);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG BROWN ', 2, 'LUSTRUIT', 'LASTRE', 337.5, 401.63);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG BROWN ', 3, 'LUSTRUIT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG BROWN ', 2, 'FIAMAT', 'SEMILASTRE', 236.25, 281.14);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG BROWN ', 2, 'LUSTRUIT', 'SEMILASTRE', 225, 267.75);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG BROWN ', 3, 'FIAMAT', 'SEMILASTRE', 326.25, 388.24);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG BROWN ', 3, 'LUSTRUIT', 'SEMILASTRE', 303.75, 361.46);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG DARK', 2, 'LUSTRUIT', 'LASTRE', 422.5, 502.78);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG DARK', 3, 'LUSTRUIT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG DARK', 2, 'FIAMAT', 'SEMILASTRE', 275, 327.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG DARK', 2, 'LUSTRUIT', 'SEMILASTRE', 265, 315.35);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG DARK', 3, 'FIAMAT', 'SEMILASTRE', 489.38, 582.36);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG DARK', 3, 'LUSTRUIT', 'SEMILASTRE', 528.75, 629.21);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG YELLOW ', 2, 'LUSTRUIT', 'LASTRE', 605, 719.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG YELLOW ', 3, 'LUSTRUIT', 'LASTRE', 1056.25, 1256.94);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG YELLOW ', 2, 'FIAMAT', 'SEMILASTRE', 317.5, 377.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG YELLOW ', 2, 'LUSTRUIT', 'SEMILASTRE', 317.5, 377.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG YELLOW ', 3, 'FIAMAT', 'SEMILASTRE', 416.25, 495.34);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PADANG YELLOW ', 3, 'LUSTRUIT', 'SEMILASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PALOMINO', 2, 'LUSTRUIT', 'LASTRE', 2205, 2623.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PARADISO BASH', 2, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PARADISO BASH', 3, 'LUSTRUIT', 'LASTRE', 753.75, 896.96);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PARADISO BASH', 2, 'LUSTRUIT', 'SEMILASTRE', 337.5, 401.63);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PARADISO CLASSIC', 2, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PARADISO CLASSIC', 3, 'LUSTRUIT', 'LASTRE', 753.75, 896.96);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PARADISO CLASSIC', 2, 'LUSTRUIT', 'SEMILASTRE', 337.5, 401.63);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PARADISO CLASSIC', 3, 'LUSTRUIT', 'SEMILASTRE', 489.38, 582.36);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEACH RED ', 2, 'FIAMAT', 'SEMILASTRE', 202.5, 240.98);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEACH RED ', 2, 'LUSTRUIT', 'SEMILASTRE', 202.5, 240.98);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEACH RED ', 3, 'FIAMAT', 'SEMILASTRE', 360, 428.4);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEACH RED ', 3, 'LUSTRUIT', 'SEMILASTRE', 360, 428.4);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PAU BRASIL', 3, 'LUSTRUIT', 'LASTRE', 450, 535.5);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEACOCK GREEN', 2, 'LUSTRUIT', 'LASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEARL FLOWER ', 2, 'FIAMAT', 'SEMILASTRE', 168.75, 200.81);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEARL FLOWER ', 2, 'LUSTRUIT', 'SEMILASTRE', 168.75, 200.81);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEARL FLOWER ', 3, 'FIAMAT', 'SEMILASTRE', 326.25, 388.24);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEARL FLOWER', 3, 'LUSTRUIT', 'SEMILASTRE', 303.75, 361.46);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEGASUS', 2, 'LUSTRUIT', 'LASTRE', 708.75, 843.41);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PEGASUS', 3, 'LUSTRUIT', 'LASTRE', 770.63, 917.04);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PLATINIUM', 2, 'LUSTRUIT', 'LASTRE', 1327.5, 1579.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'PORTOFINO BROWN', 3, 'LUSTRUIT', 'LASTRE', 450, 535.5);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'RED DRAGON', 2, 'LUSTRUIT', 'LASTRE', 1642.5, 1954.58);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'REVOLUTION WAVE', 2, 'LUSTRUIT', 'LASTRE', 2362.5, 2811.38);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ROCKY MOUNTAIN', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ROMA IMPERIALE', 3, 'LUSTRUIT', 'LASTRE', 1113.75, 1325.36);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ROSA PORRINO', 2, 'FIAMAT', 'LASTRE', 348.75, 415.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ROSA PORRINO', 2, 'LUSTRUIT', 'LASTRE', 348.75, 415.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ROSA PORRINO', 3, 'FIAMAT', 'LASTRE', 573.75, 682.76);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ROSA PORRINO', 3, 'LUSTRUIT', 'LASTRE', 562.5, 669.38);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ROYAL WHITE', 2, 'LUSTRUIT', 'LASTRE', 663.75, 789.86);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'ROYAL WHITE', 3, 'LUSTRUIT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'RUBY RED', 2, 'FIAMAT', 'LASTRE', 663.75, 789.86);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'RUBY RED', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'RUBY RED', 3, 'FIAMAT', 'LASTRE', 945, 1124.55);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'RUBY RED', 3, 'LUSTRUIT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SANDALUS', 2, 'PERIAT', 'LASTRE', 1113.75, 1325.36);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SANTA CECILIA S', 3, 'LUSTRUIT', 'LASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SANTA CECILIA S', 3, 'PERIAT', 'LASTRE', 716.25, 852.34);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SANTA CECILIA', 2, 'LUSTRUIT', 'LASTRE', 412.5, 490.88);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SANTA CECILIA', 2, 'PERIAT', 'LASTRE', 547.5, 651.53);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SANTA HELENA', 3, 'LUSTRUIT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SANTORINI', 2, 'LUSTRUIT', 'LASTRE', 2385, 2838.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SHIVA GOLD', 2, 'LUSTRUIT', 'LASTRE', 573.75, 682.76);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SMOOGA RED', 2, 'LUSTRUIT', 'LASTRE', 613.13, 729.62);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SNOW FALL', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SNOW FALL', 3, 'LUSTRUIT', 'LASTRE', 753.75, 896.96);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SOFT YELLOW', 3, 'LUSTRUIT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SPLENDOUR WHITE', 3, 'LUSTRUIT', 'LASTRE', 1743.75, 2075.06);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'STEEL GREY', 2, 'LUSTRUIT', 'LASTRE', 506.25, 602.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'STEEL GREY', 2, 'PERIAT', 'LASTRE', 540, 642.6);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'STEEL GREY', 3, 'LUSTRUIT', 'LASTRE', 680.63, 809.94);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'STEEL GREY', 3, 'PERIAT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'STRAWBERRY', 2, 'LUSTRUIT', 'LASTRE', 540, 642.6);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SURF GREEN', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'SURF GREEN', 3, 'LUSTRUIT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TAN BLACK', 2, 'LUSTRUIT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TAN BLACK', 3, 'LUSTRUIT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TAN BLACK', 2, 'LUSTRUIT', 'SEMILASTRE', 348.75, 415.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TAN BROWN', 2, 'LUSTRUIT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TAN BROWN', 3, 'LUSTRUIT', 'LASTRE', 455, 541.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TAN BROWN', 2, 'FIAMAT', 'SEMILASTRE', 365.63, 435.09);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TAN BROWN', 2, 'LUSTRUIT', 'SEMILASTRE', 350, 416.5);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TAN BROWN', 3, 'LUSTRUIT', 'SEMILASTRE', 506.25, 602.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TEMPEST GOLD', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIBET WHITE', 3, 'LUSTRUIT', 'LASTRE', 1046.25, 1245.04);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIGER BROWN', 2, 'LUSTRUIT', 'LASTRE', 506.25, 602.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIGER BROWN', 1.8, 'LUSTRUIT', 'SEMILASTRE', 360, 428.4);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIGER SKIN RED', 2, 'FIAMAT', 'SEMILASTRE', 292.5, 348.08);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIGER SKIN RED', 2, 'LUSTRUIT', 'SEMILASTRE', 292.5, 348.08);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIGER SKIN RED', 3, 'FIAMAT', 'SEMILASTRE', 433.13, 515.42);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIGER SKIN RED', 3, 'LUSTRUIT', 'SEMILASTRE', 438.75, 522.11);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIJUCA CREAM', 2, 'LUSTRUIT', 'LASTRE', 742.5, 883.58);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIJUCA CREAM', 3, 'LUSTRUIT', 'LASTRE', 967.5, 1151.33);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TIMBALADA', 2, 'LUSTRUIT', 'LASTRE', 776.25, 923.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TITANIUM', 2, 'LUSTRUIT', 'LASTRE', 843.75, 1004.06);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TITANIUM', 2, 'PERIAT', 'LASTRE', 843.75, 1004.06);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TITANIUM', 3, 'LUSTRUIT', 'LASTRE', 1288.13, 1532.87);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TOBLERONE BIANCO', 2, 'LUSTRUIT', 'LASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TROPIC BROWN', 3, 'LUSTRUIT', 'LASTRE', 821.25, 977.29);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TYPHOON BORDEAUX LIGHT', 2, 'LUSTRUIT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'TYPHOON BORDEAUX SIENNA', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VALLE NEVADO', 2, 'LUSTRUIT', 'LASTRE', 382.5, 455.18);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VALLE NEVADO', 3, 'LUSTRUIT', 'LASTRE', 450, 535.5);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VERDE BAHIA S', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VERDE BAHIA S', 3, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VERDE BAHIA ', 2, 'LUSTRUIT', 'LASTRE', 551.25, 655.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VERDE BAHIA ', 3, 'LUSTRUIT', 'LASTRE', 798.75, 950.51);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VEYRON', 3, 'LUSTRUIT', 'LASTRE', 967.5, 1151.33);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VIA LACTEA', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VIA LACTEA', 3, 'LUSTRUIT', 'LASTRE', 708.75, 843.41);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VIENNA', 3, 'LUSTRUIT', 'LASTRE', 1046.25, 1245.04);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VIOLETA', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VIZAG BLUE', 2, 'LUSTRUIT', 'LASTRE', 585, 696.15);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VIZAG BLUE', 3, 'LUSTRUIT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VOLCANO RED', 2, 'LUSTRUIT', 'LASTRE', 720, 856.8);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'VOLCANO RED', 1.8, 'LUSTRUIT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE GALAXY', 3, 'LUSTRUIT', 'LASTRE', 663.75, 789.86);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE ICE', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE ICE', 3, 'LUSTRUIT', 'LASTRE', 1305, 1552.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE PERSA', 2, 'LUSTRUIT', 'LASTRE', 708.75, 843.41);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE SPLASH', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE SPLASH', 3, 'LUSTRUIT', 'LASTRE', 1305, 1552.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE SPLASH', 2, 'PERIAT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE TORRONCINO', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WHITE VIENA', 2, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'WILD SEA', 2, 'LUSTRUIT', 'LASTRE', 1327.5, 1579.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IRAN GRI', 2, 'LUSTRUIT', 'LASTRE', 200, 238);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('GRANIT', 'IRAN VERDE', 2, 'LUSTRUIT', 'LASTRE', 200, 238);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ALASKA A1', 2, 'LUSTRUIT', 'LASTRE', 500.63, 595.74);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ALASKA A2', 2, 'LUSTRUIT', 'LASTRE', 438.75, 522.11);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ALEXANDER', 2, 'LUSTRUIT', 'LASTRE', 371.25, 441.79);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ALEXANDER', 3, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ALIGATOR', 2, 'LUSTRUIT', 'LASTRE', 573.75, 682.76);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ARABESCATO BEIGE', 2, 'LUSTRUIT', 'LASTRE', 371.25, 441.79);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ARABESCATO WHITE', 2, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ARABESQUE', 2, 'LUSTRUIT', 'LASTRE', 438.75, 522.11);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ARTESIAN', 2, 'LUSTRUIT', 'LASTRE', 922.5, 1097.78);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ATHENS GREY', 2, 'LUSTRUIT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ATHENS GREY', 3, 'LUSTRUIT', 'LASTRE', 641.25, 763.09);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'BIANCO SARDA', 2, 'LUSTRUIT', 'LASTRE', 450, 535.5);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'BLACK TORROS', 2, 'LUSTRUIT', 'LASTRE', 607.5, 722.93);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'BLANCO IBIZA', 2, 'LUSTRUIT', 'LASTRE', 348.75, 415.01);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'BLUE SKY', 2, 'LUSTRUIT', 'LASTRE', 438.75, 522.11);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'BOTTICINO', 2, 'LUSTRUIT', 'LASTRE', 573.75, 682.76);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'BOTTICINO', 3, 'LUSTRUIT', 'LASTRE', 1001.25, 1191.49);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CAPUCCINO', 2, 'LUSTRUIT', 'LASTRE', 416.25, 495.34);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CARRARA CD', 2, 'LUSTRUIT', 'LASTRE', 731.25, 870.19);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CARRARA VENATINO', 2, 'LUSTRUIT', 'LASTRE', 1822.5, 2168.78);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CIPOLINO', 2, 'LUSTRUIT', 'LASTRE', 1901.25, 2262.49);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CREMA MARFIL ', 2, 'LUSTRUIT', 'LASTRE', 315, 374.85);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CREMA MARFIL ', 3, 'LUSTRUIT', 'LASTRE', 697.5, 830.03);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CREMA NOVA', 2, 'LUSTRUIT', 'LASTRE', 528.75, 629.21);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CREMA NOVA', 3, 'LUSTRUIT', 'LASTRE', 753.75, 896.96);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CRYSTAL WHITE', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'CRYSTAL WHITE', 3, 'LUSTRUIT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'EMPERADOR DARK', 2, 'LUSTRUIT', 'LASTRE', 405, 481.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'EMPERADOR DARK', 3, 'LUSTRUIT', 'LASTRE', 641.25, 763.09);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'EMPERADOR LIGHT', 2, 'LUSTRUIT', 'LASTRE', 461.25, 548.89);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'EMPERADOR LIGHT', 3, 'LUSTRUIT', 'LASTRE', 742.5, 883.58);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ERA SILVER', 3, 'LUSTRUIT', 'LASTRE', 1001.25, 1191.49);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'EQUADOR', 2, 'LUSTRUIT', 'LASTRE', 534.38, 635.91);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ERAMOSA C/C', 2, 'LUSTRUIT', 'LASTRE', 2767.5, 3293.33);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ERAMOSA V/C', 2, 'LUSTRUIT', 'LASTRE', 2666.25, 3172.84);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'FANTASTICO BEJ', 2, 'LUSTRUIT', 'LASTRE', 551.25, 655.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'FANTASY BROWN', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'GOLDEN SPIDER', 2, 'LUSTRUIT', 'LASTRE', 832.5, 990.68);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'GRAFITE', 2, 'LUSTRUIT', 'LASTRE', 697.5, 830.03);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'GRIGIO', 2, 'LUSTRUIT', 'LASTRE', 247.5, 294.53);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'KARNEZEIKA', 2, 'LUSTRUIT', 'LASTRE', 540, 642.6);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'LAZIZE', 2, 'LUSTRUIT', 'LASTRE', 686.25, 816.64);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'LAZIZE', 2, 'PERIAT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'LAZIZE', 3, 'LUSTRUIT', 'LASTRE', 967.5, 1151.33);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'LAZIZE', 3, 'PERIAT', 'LASTRE', 990, 1178.1);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'LILAC', 2, 'LUSTRUIT', 'LASTRE', 1305, 1552.95);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'LOTUS BEIGE', 2, 'LUSTRUIT', 'LASTRE', 450, 535.5);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'LOTUS BEIGE', 3, 'LUSTRUIT', 'LASTRE', 596.25, 709.54);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'MARFILIO', 2, 'LUSTRUIT', 'LASTRE', 371.25, 441.79);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'MARFILIO', 3, 'LUSTRUIT', 'LASTRE', 506.25, 602.44);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'MARON EMPERADOR', 2, 'LUSTRUIT', 'LASTRE', 607.5, 722.93);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'MARON EMPERADOR', 3, 'LUSTRUIT', 'LASTRE', 911.25, 1084.39);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'MISTY WHITE', 2, 'LUSTRUIT', 'LASTRE', 517.5, 615.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'NERO MARQUINA', 2, 'LUSTRUIT', 'LASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'NERO MARQUINA', 3, 'LUSTRUIT', 'LASTRE', 596.25, 709.54);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'NOTTE STELLATA', 2, 'LUSTRUIT', 'LASTRE', 483.75, 575.66);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'NOTTE STELLATA', 3, 'LUSTRUIT', 'LASTRE', 562.5, 669.38);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'NOTTE STELLATA', 3, 'PERIAT', 'LASTRE', 562.5, 669.38);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'NUVOLA BIANCO', 2, 'LUSTRUIT', 'LASTRE', 1170, 1392.3);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'OLYMPUS BEIGE', 2, 'LUSTRUIT', 'LASTRE', 461.25, 548.89);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'OLYMPUS BEIGE', 3, 'LUSTRUIT', 'LASTRE', 618.75, 736.31);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'OLYMPUS COFFEE', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PERLA', 2, 'LUSTRUIT', 'LASTRE', 461.25, 548.89);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PIRGON ARABESQUE', 2, 'LUSTRUIT', 'LASTRE', 1046.25, 1245.04);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PIRGON NIMBUS', 2, 'LUSTRUIT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PITSILA', 2, 'LUSTRUIT', 'LASTRE', 292.5, 348.08);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PITSILA', 2, 'NELUSTRUIT', 'LASTRE', 247.5, 294.53);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PRATA', 2, 'LUSTRUIT', 'LASTRE', 416.25, 495.34);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PRATA', 3, 'LUSTRUIT', 'LASTRE', 556.88, 662.68);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PURPLE BROWN', 2, 'LUSTRUIT', 'LASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PURPLE BROWN', 2, 'PERIAT', 'LASTRE', 472.5, 562.28);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'RAINFOREST BROWN', 2, 'LUSTRUIT', 'LASTRE', 528.75, 629.21);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'RAINFOREST BROWN', 2, 'PERIAT', 'LASTRE', 596.25, 709.54);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'RAINFOREST BROWN', 3, 'LUSTRUIT', 'LASTRE', 742.5, 883.58);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'RAINFOREST BROWN', 3, 'PERIAT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'RAINFOREST GREEN', 2, 'LUSTRUIT', 'LASTRE', 528.75, 629.21);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'RAINFOREST GREEN', 2, 'PERIAT', 'LASTRE', 596.25, 709.54);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'RAINFOREST GREEN', 3, 'LUSTRUIT', 'LASTRE', 742.5, 883.58);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'RAINFOREST GREEN', 3, 'PERIAT', 'LASTRE', 855, 1017.45);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ROSALIA', 2, 'LUSTRUIT', 'LASTRE', 573.75, 682.76);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ROSO ALICANTE', 2, 'LUSTRUIT', 'LASTRE', 911.25, 1084.39);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'ROYAL YELLOW', 2, 'LUSTRUIT', 'LASTRE', 832.5, 990.68);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'SHADOW STORM', 2, 'LUSTRUIT', 'LASTRE', 495, 589.05);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'SIENA BROWN', 2, 'LUSTRUIT', 'LASTRE', 551.25, 655.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'SUPER CALACATA', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TABACCO', 2, 'LUSTRUIT', 'LASTRE', 551.25, 655.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TESORO BLUE', 2, 'LUSTRUIT', 'LASTRE', 393.75, 468.56);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'THASSOS SELECT', 2, 'LUSTRUIT', 'LASTRE', 2351.25, 2797.99);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TIMBER BROWN', 2, 'LUSTRUIT', 'LASTRE', 630, 749.7);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TIMBER BROWN', 3, 'LUSTRUIT', 'LASTRE', 956.25, 1137.94);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TIMBER YELLOW', 2, 'LUSTRUIT', 'LASTRE', 427.5, 508.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'VENATINO STATUARIETTO', 2, 'LUSTRUIT', 'LASTRE', 1417.5, 1686.83);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'VERDE INDIA', 2, 'LUSTRUIT', 'LASTRE', 360, 428.4);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'VERDE INDIA', 3, 'LUSTRUIT', 'LASTRE', 528.75, 629.21);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'VERDE TROPICUS', 2, 'LUSTRUIT', 'LASTRE', 1023.75, 1218.26);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'VERIA GREEN', 2, 'LUSTRUIT', 'LASTRE', 663.75, 789.86);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'WHITE TIGER BRINDLE SEBERIANO', 2, 'LUSTRUIT', 'LASTRE', 675, 803.25);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'SUNNY MENIA', 2, 'LUSTRUIT', 'LASTRE', 151.88, 180.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'SYLVIA MENIA', 2, 'LUSTRUIT', 'LASTRE', 151.88, 180.73);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TRIESTA/SINAI PEARL', 2, 'LUSTRUIT', 'LASTRE', 191.25, 227.59);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'GALLALA', 2, 'LUSTRUIT', 'LASTRE', 185.63, 220.89);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TRAVERTINE BEIGE Vc', 2, 'LUSTRUIT', 'LASTRE', 325, 386.75);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TRAVERTINE BEIGE CC', 2, 'LUSTRUIT', 'LASTRE', 325, 386.75);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TRAVERTINE NOCE', 2, 'LUSTRUIT', 'LASTRE', 325, 386.75);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'TRAVERTINE YELLOW', 2, 'LUSTRUIT', 'LASTRE', 325, 386.75);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'VOLAKAS', 2, 'LUSTRUIT', 'LASTRE', 256.25, 304.94);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'KAVALA', 2, 'LUSTRUIT', 'LASTRE', 243.75, 290.06);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'THASSOS CRYSTAL', 2, 'LUSTRUIT', 'LASTRE', 468.75, 557.81);
INSERT INTO MATERIALS(type, name, thickness, surface, finish, price, priceVat) VALUES('MARMURA', 'PIGHES WHITE', 2, 'LUSTRUIT', 'LASTRE', 343.75, 409.06);
