INSERT into workmanshipprices(code, name, price) VALUES(1,'SEMIBASTON',20);
INSERT into workmanshipprices(code, name, price) VALUES(2,'BIZOT',10);
INSERT into workmanshipprices(code, name, price) VALUES(3,'PROFIL SPECIAL',15);
INSERT into workmanshipprices(code, name, price) VALUES(4,'PICURATOR',4);
INSERT into workmanshipprices(code, name, price) VALUES(5,'TAIAT',36);
INSERT into workmanshipprices(code, name, price) VALUES(6,'DECUPAJE LAVOARE',57);
INSERT into workmanshipprices(code, name, price) VALUES(7,'DECUPAJE PE CURB',10);
INSERT into workmanshipprices(code, name, price) VALUES(8,'GAURI CAROTA',10);
INSERT into workmanshipprices(code, name, price) VALUES(9,'LIPIRE ADAOS',15);
INSERT into workmanshipprices(code, name, price) VALUES(10,'CANAL ANTIDERAPANT',4);
